// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using Foundation;
using PullToRefresh.Models;
using UIKit;

namespace PullToRefresh
{
    public partial class citiesTableViewController : UITableViewController
    {
        string Identifier = "cell";
        #region Variable
        UIRefreshControl refreshControl;
        Dictionary<string, List<string>> cities;
        #endregion
        public citiesTableViewController(IntPtr handle) : base(handle)
        {
        }
        #region Life Cycle
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            //Mostrar la ciudades que tiene por default la app
            InitializeComponents();
        }
        #endregion

        #region User Interactions
        void RefreshControl_ValueChanged(object sender, EventArgs e)
        {
            CitiesManager.SharedInstance.FetchCities();

        }
        #endregion
        #region Table view
        [Export("numberOfSectionsInTableView:")]
        public nint NumberOfSections(UITableView tableView)
        {
            return cities.Keys.Count;
        }
        public override string TitleForHeader(UITableView tableView, nint section)
        {
            return cities.Keys.ElementAt((int)section);
        }
        public override nint RowsInSection(UITableView tableView, nint section)
        {

            string key = cities.Keys.ElementAt((int)section);
            return cities[key].Count;

            //int result = cities.Values.Sum(list => list.Count);
            //return 0;
        }
        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
           UITableViewCell cell = tableView.DequeueReusableCell(Identifier);
            if (cell == null)
                cell = new UITableViewCell(UITableViewCellStyle.Subtitle, Identifier);

            cell.TextLabel.Text = cities[cities.Keys.ElementAt(indexPath.Section)].ElementAt(indexPath.Row);

            return cell;
        }

        [Export("sectionIndexTitlesForTableView:")]
        public string[] SectionIndexTitles(UITableView tableView)
        {
            return new List<string>(cities.Keys).ToArray();
        }




        void CitiesManager_CitiesFetched(object sender, CitiesManager.CitiesEventArgs e)
        {
            cities = e.Cities;
            InvokeOnMainThread(() => refreshControl.EndRefreshing());
        }

        void CitiesManager_FetchCitiesFaild(object sender, EventArgs e)
        {
            Console.WriteLine("Something faild");
            InvokeOnMainThread(() => refreshControl.EndRefreshing());
        }


        #endregion

        #region Internal funcionallity
        void InitializeComponents()
        {
            CitiesManager.SharedInstance.CitiesFetched += CitiesManager_CitiesFetched;
            CitiesManager.SharedInstance.FetchCitiesFaild+=CitiesManager_FetchCitiesFaild;
            //ciudades por default
            cities = CitiesManager.SharedInstance.GetDefaultCities();
            refreshControl = new UIRefreshControl();
            refreshControl.ValueChanged += RefreshControl_ValueChanged;
            TableView.RefreshControl = refreshControl;
        }
        #endregion
    }
}
